import type {Metadata} from "next"
import {Prompt, Work_Sans} from "next/font/google"
import "../styles/main.scss"
import Navbar from "@/components/navbar/navbar"

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${prompt.variable} ${workSans.variable}`}>{children}</body>
    </html>
  )
}
